In [3]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [7]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [9]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [15]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [51]:
np.random.seed(10)
np.random.random((4, 4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [33]:
c = np.linspace(0, 5, 10)
print(c.shape)

(10,)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [35]:
a = np.arange(16)
a.reshape((4, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [37]:
a = np.arange(16)
print(a.dtype)

int32


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [65]:
# a = np.arange(1, 101)
# for i in a:
#     if i % 2 == 0:
#         print(i, end = " ")

np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [84]:
np.random.seed(0)
np.random.randint(10, 50, (6,6))

array([[10, 13, 13, 49, 19, 29],
       [31, 46, 33, 16, 34, 34],
       [22, 11, 48, 49, 33, 34],
       [27, 47, 35, 23, 18, 19],
       [30, 26, 15, 25, 10, 28],
       [45, 34, 39, 29, 29, 24]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [86]:
np.random.seed(0)
y = np.random.randint(10, 50, (6,6))
b = y[1:4, 2:]
b

array([[33, 16, 34, 34],
       [48, 49, 33, 34],
       [35, 23, 18, 19]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [53]:
np.random.seed(0)
x = np.random.randint(10, size=(3, 4))
np.sum(x)

64

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [63]:
print(np.mean(x), np.median(x), np.std(x))

4.5 4.5 2.3979157616563596


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [69]:
print(np.max(x), np.min(x))

9 0


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [166]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20)
print(a)
# print(np.where(a == np.max(a)))
np.argmax(a)

[44 47  0  3  3 39  9 19 21 36 23  6 24 24 12  1 38 39 23 46]


1

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [174]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4,5)
np.flip(a)

array([[46, 23, 39, 38,  1],
       [12, 24, 24,  6, 23],
       [36, 21, 19,  9, 39],
       [ 3,  3,  0, 47, 44]])

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [126]:
a = np.random.randint(1, 9, (3,3))
b = np.random.randint(5, 15, (3,3))
a * b

array([[30, 36, 48],
       [56, 56, 12],
       [14, 10, 10]])

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [128]:
a = np.arange(16)
a.reshape(4, 4) * np.eye(4, 4)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 15.]])

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [130]:
a = np.random.randint(1, 9, (3,3))
b = np.random.randint(5, 15, (3,3))
np.dot(a, b)

array([[190, 185, 180],
       [174, 143, 111],
       [146, 162, 179]])

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20

In [154]:
a = np.random.randint(1, 9, (3,3))
print(a)
print(a.flatten())

[[3 4 7]
 [2 3 2]
 [5 3 7]]
[3 4 7 2 3 2 5 3 7]


---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [184]:
np.random.seed(0)
a = np.random.randint(1, 9, (3,3))
b = np.random.randint(5, 15, (3,3))
np.row_stack((a, b))

array([[ 5,  6,  6],
       [ 7,  1,  5],
       [ 2,  8,  5],
       [14, 13,  6],
       [ 6, 12, 14],
       [14,  8, 11]])

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [186]:
np.column_stack((a, b))

array([[ 5,  6,  6, 14, 13,  6],
       [ 7,  1,  5,  6, 12, 14],
       [ 2,  8,  5, 14,  8, 11]])

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [216]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4, 5)
np.split(a, [2, 3])

[array([[44, 47,  0,  3,  3],
        [39,  9, 19, 21, 36]]),
 array([[23,  6, 24, 24, 12]]),
 array([[ 1, 38, 39, 23, 46]])]

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [208]:
A = np.random.random((3, 4))
np.round(A, 2)

array([[0.12, 0.64, 0.14, 0.94],
       [0.52, 0.41, 0.26, 0.77],
       [0.46, 0.57, 0.02, 0.62]])

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [218]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20)
np.unique(a)

array([ 0,  1,  3,  6,  9, 12, 19, 21, 23, 24, 36, 38, 39, 44, 46, 47])

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [224]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4, 5)
print(a)
print("==================================================")
a[a < 10] = 10
print(a)

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
[[44 47 10 10 10]
 [39 10 19 21 36]
 [23 10 24 24 12]
 [10 38 39 23 46]]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [226]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4, 5)
np.cumsum(a)

array([ 44,  91,  91,  94,  97, 136, 145, 164, 185, 221, 244, 250, 274,
       298, 310, 311, 349, 388, 411, 457])

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [176]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20)
np.count_nonzero(a)

19

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [178]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20)
np.sort(a)

array([ 0,  1,  3,  3,  6,  9, 12, 19, 21, 23, 23, 24, 24, 36, 38, 39, 39,
       44, 46, 47])

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [222]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4, 5)
print(a)
print("==================================================")
print(np.sum(a, axis = 0))
print("==================================================")
print(np.sum(a, axis = 1))

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
[107 100  82  71  97]
[ 97 124  89 147]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [231]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4, 5)
a_norm = a / np.linalg.norm(a)
a_norm

array([[0.35531275, 0.37953861, 0.        , 0.02422587, 0.02422587],
       [0.3149363 , 0.07267761, 0.1534305 , 0.16958108, 0.29071043],
       [0.18573166, 0.04845174, 0.19380695, 0.19380695, 0.09690348],
       [0.00807529, 0.30686101, 0.3149363 , 0.18573166, 0.37146332]])

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [243]:
a = np.random.randint(1, 10, (5,))
b = np.random.randint(1, 10, (5,))
print(a)
print(b)
print("==================================")
print(np.dot(a, b))

[8 4 7 8 3]
[1 4 6 5 5]
121


---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [247]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4, 5)
print(a)
print("=======================================")
print(np.trace(a))

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
100


---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [261]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 20).reshape(4, 5)
print(a)
print("==========================================")
a[[2, 1]] = a[[1, 2]]
print(a)

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
[[44 47  0  3  3]
 [23  6 24 24 12]
 [39  9 19 21 36]
 [ 1 38 39 23 46]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [291]:
a = np.arange(4)
print(a)
print(a[:, np.newaxis])

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [283]:
a = np.random.randint(0, 9, (3,3))
np.linalg.det(a)

24.999999999999986

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

In [275]:
np.random.seed(0)
a = np.random.randint(2, 10, size = 4).reshape(2, 2)
print("Eigenvalues: {} \nEigenvectors: {}".format(np.linalg.eig(a)[0], np.linalg.eig(a)[1]))

Eigenvalues: [12.18535277 -4.18535277] 
Eigenvectors: [[ 0.82413371 -0.6621561 ]
 [ 0.5663953   0.74936594]]


---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

In [279]:
A = np.array([[1, 1], [1, -1]])
B = np.array([[5], [1]])
np.linalg.solve(A, B)

array([[3.],
       [2.]])

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

In [265]:
np.random.seed(0)
a = np.random.randint(0, high = 50, size = 16).reshape(4, 4)
np.diagonal(a)

array([44, 39, 23,  1])